on: [push, pull_request]
jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [ '3.7', '3.8', '3.9', '3.10' ]
        tox-version: [ '3.*', '4.*' ]
    name: Tox ${{ matrix.tox-version }} plugin - Python ${{ matrix.python-version }}
    steps:
      - uses: actions/checkout@v2
      - name: Setup python
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}
      - name: Run tox
        working-directory: tests/tox-plugin
        run: |
          python -m pip install "tox==${{ matrix.tox-version }}"
          python -m tox
